gnkc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('student/', include('students.urls')),
    path('teacher', include('teachers.urls')),
    path('quizzes/', include('quiz.urls')),
    path('homework/', include('homework.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<int:quizID>', views.quiz, name='quiz'),
    path('submit', views.submit, name='submit'),
    path('create', views.create, name='create'),
    path('add', views.addQuestion, name='add_Question'),
    path('delete/question/<int:questionID>',
         views.deleteQuestion, name="delete_Question"),
    path('delete/quiz/<int:quizID>', views.deleteQuiz, name="delete_Quiz"),
    path('update/quiz/<int:quizID>', views.updateQuiz, name="update_Quiz"),
    path('update/question/<int:questionID>',
         views.updateQuestion, name="update_Question"),
]

quiz/models.py
from django.db import models
from teachers.models import Teacher


class Quiz(models.Model):
	levelOptions = (
            ('1', 'Level 1'),
         			('2', 'Level 2'),
         			('3', 'Level 3'),
         			('4', 'Level 4'),
         			('5', 'Level 5'),
         			('6', 'Level 6'),
         			('7', 'GCSE'),
         			('8', 'AS-Level'),
         			('9', 'A-Level'),
      					 ('10', 'All'),
        )

	classOptions = (
            ('1', 'Sat AM'),
         			('2', 'Sat PM'),
         			('3', 'Sun AM'),
         			('4', 'Sun PM'),
        				('5', 'All')
        )
	title = models.CharField(max_length=100)
	teacher = models.ForeignKey(
            Teacher, unique=False, on_delete=models.CASCADE)
	classes = models.CharField(
            max_length=2, choices=classOptions, default=1)
	level = models.CharField(max_length=2, choices=levelOptions, default=1)
	image_path = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)

	def __str__(self):
		return self.title


class Question(models.Model):
	answerOptions = (
            ('1', 'answer_1'),
            ('2', 'answer_2'),
            ('3', 'answer_3'),
            ('4', 'answer_4'),
        )
	quiz = models.ForeignKey(Quiz, unique=False, on_delete=models.CASCADE)
	title = models.CharField(max_length=100)
	answer_1 = models.CharField(max_length=50)
	answer_2 = models.CharField(max_length=50)
	answer_3 = models.CharField(max_length=50)
	answer_4 = models.CharField(max_length=50)
	#correct_answer = models.CharField(
	#	max_length=2, choices=answerOptions, default=1)
	correct_answer = models.IntegerField()
	image_path = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)

	def __str__(self):
		return self.title

	@property
	def correct_answer_value(self):return (
            self.answer_1, self.answer_2, self.answer_3, self.answer_4
        )[self.correct_answer-1]  # add back -1

quiz/views.py
from django.contrib import messages
from django.contrib.messages.api import error
from django.http.response import Http404
from django.shortcuts import redirect, render, get_object_or_404, get_list_or_404
from .models import Question, Quiz
from teachers.models import Teacher
from students.models import Students
from score.models import Score
from quiz.form import quizForm
from quiz.questionForm import questionForm
from django.http import HttpResponseRedirect

# def filterID(ID):
#     if(question.id == questionID):
#         del questionList[index


def quiz(request, quizID):
    if request.user.is_authenticated:
        try:
            user = get_object_or_404(Students, user_id=request.user.id)
            quiz = get_object_or_404(Quiz, pk=quizID)
        except Http404:
            return redirect('index')
        try:
            # if (user.classes == quiz.classes) & (user.level == quiz.level) & (user.teacher == quiz.teacher):
            try:
                get_object_or_404(
                    Score, first_name=request.user.first_name, last_name=request.user.last_name, quiz_id=quizID)
                messages.info(request, 'You have already done this quiz')
                return redirect('/')
            except Http404:
                questionList = get_list_or_404(Question, quiz_id=quizID)
                print(questionList)
                context = {
                    'questions': questionList,
                    'quiz': quizID,
                }
                print('worked')
                return render(request, 'quiz/quiz.html', context)
        except Http404:
            messages.error(
                request, 'You are not authenticated')
            return redirect('index')
    messages.error(
        request, 'You are not authenticated')
    return redirect('index')


def create(request):
    form = quizForm()
    addQuestionForm = questionForm()
    if request.user.is_authenticated & request.user.is_staff:
        if request.method == 'POST':
            try:
                teacher_id = get_object_or_404(
                    Teacher, user_id=request.user.pk)
                quizSubmit = quizForm(request.POST, request.FILES)
                if quizSubmit.is_valid():
                    print('valid')
                    quiz_form_submit = quizSubmit.save(commit=False)
                    quiz_form_submit.teacher_id = teacher_id.pk
                    quiz_form_submit.save()
                    quiz_id = quiz_form_submit.pk
                    messages.success(request, 'Quiz Created')
                    return render(request, 'question/question.html', {'quiz_id': quiz_id, 'form': addQuestionForm})
                return redirect('quizzes')
            except:
                messages.error(
                    request, 'error in creation - please speak to admin')
                return redirect('quizzes')
        return render(request, 'quiz/createQuiz.html', {'form': form})
    messages.error(
        request, 'You are not authenticated')
    return redirect('index')


def addQuestion(request):
    addQuestionForm = questionForm()
    if request.user.is_authenticated & request.user.is_staff:
        if request.method == 'POST':
            try:
                questionSubmit = questionForm(request.POST, request.FILES)
                quizID = request.POST['quiz_id']
                quizInstance = get_object_or_404(Quiz, pk=quizID)
                if questionSubmit.is_valid():
                    question_form_submit = questionSubmit.save(commit=False)
                    question_form_submit.quiz = quizInstance
                    question_form_submit.save()
                    try:
                        quiz_Questions = get_list_or_404(Question, quiz_id=quizID)
                        context = {
                            'questions': quiz_Questions,
                            'quiz_id': quizID,
                            'form': addQuestionForm
                        }
                    except Http404:
                        context = {
                            'quiz_id': quizID,
                            'form': addQuestionForm
                        }
                    return render(request, 'question/question.html', context)
                return render(request, 'question/question.html', {'quiz_id': quizID, 'form': addQuestionForm})
            except:
                messages.error(
                    request, 'error in creation - please speak to admin')
                return redirect('quizzes')
    messages.error(request, 'You are not authenticated')
    return redirect('quizzes')


def deleteQuestion(request, questionID):
    addQuestionForm = questionForm()
    if request.user.is_authenticated & request.user.is_staff:
        question = Question.objects.get(id=questionID)
        quizID = question.quiz_id
        question.delete()
        return render(request, 'question/question.html', {'id': quizID, 'form': addQuestionForm})
    messages.error(
        request, 'You are not authenticated')
    return redirect('index')


def deleteQuiz(request, quizID):
    if request.user.is_authenticated & request.user.is_staff:
        quiz = Quiz.objects.get(id=quizID)
        quiz.delete()
        messages.success(
            request, 'quiz deleted')
        return redirect('quizzes')
    messages.error(
        request, 'You are not authenticated')
    return redirect('index')


def updateQuiz(request, quizID):
    if request.user.is_authenticated & request.user.is_staff:
        try:
            quiz = get_object_or_404(Quiz, id=quizID)
            try:
                scores = get_list_or_404(Score, quiz=quizID)
            except:
                scores = ''
        except Http404:
            messages.error(
                request, 'Error in finding quiz - speak to admin')
            return redirect('quizzes')

        if request.method == 'POST':
            form = quizForm(request.POST or None,
                            request.FILES or None, instance=quiz)
            if form.is_valid():
                form.save()
                return redirect('quizzes')
        try:
            questionList = get_list_or_404(Question, quiz=quizID)
        except Http404:
            questionList = ''
        # checks if questionList exisits
        data = {
            'title': quiz.title,
            'classes': quiz.classes,
            'level': quiz.level,
            'image_path': quiz.image_path,
        }
        preFilledForm = quizForm(initial=data)
        context = {
            'form': preFilledForm,
            'id': quizID,
            'questions': questionList,
            'scores': scores,
        }
        return render(request, 'quiz/createQuiz.html', context)
    messages.error(
        request, 'You are not authenticated')

    return redirect('index')


def updateQuestion(request, questionID):
    if request.user.is_authenticated & request.user.is_staff:
        question = get_object_or_404(Question, id=questionID)
        if request.method == 'POST':
            form = questionForm(request.POST or None,
                                request.FILES or None, instance=question)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        try:
            questionList = get_list_or_404(Question, quiz_id=question.quiz_id)
            filtered_QuestionList = [
                value for value in questionList if not value.id == questionID]
            data = {
                'title': question.title,
                'answer_1': question.answer_1,
                'answer_2': question.answer_2,
                'answer_3': question.answer_3,
                'answer_4': question.answer_4,
                'correct_answer': question.correct_answer,
                'image_path': question.image_path,
            }
            preFilledForm = questionForm(initial=data)
            context = {
                'form': preFilledForm,
                'id': questionID,
                'quiz_id': question.quiz_id,
                'questions': filtered_QuestionList,
            }
            return render(request, 'question/question.html', context)
        except Http404:
            messages.error(
                request, 'could not find questions - speak to admin')

            return redirect('index')
    return redirect('index')


def submit(request):
    # TODO make it so if the question is wrong -- add it to a dict and show on page.
    if request.method == 'POST':
        score = 0
        question = {}
        wrongAnswerList = []
        submitted = {answer: request.POST[answer] for answer in request.POST.keys(
        ) - {'csrfmiddlewaretoken', 'id'}}

        for id in submitted:
            question = get_object_or_404(Question, id=id)
            if (str(question.correct_answer) == submitted[id]):
                score = score + 1
            else:
                wrongAnswerList.append(question)
        try:
            quizValues = get_object_or_404(Quiz, pk=question.quiz.pk)
            Score.objects.create(score=score, quiz=quizValues, teacher=quizValues.teacher,
                                 first_name=request.user.first_name, last_name=request.user.last_name)
        except Http404:
            messages.error(
                request, 'Error in sending results - speak to admin')
            return redirect('quizzes')
        # submitScore.save()
        context = {
            'wrongAnswer': wrongAnswerList,
            'score': score
        }
        return render(request, 'quiz/submitted.html', context)
    return redirect('quizzes')

    # try: looping dict useful

    #     question = Question.objects.get(id=questionID)

    #     formatted_values = {value: request.POST[value] for value in request.POST.key(

    #     ) - {'csrfmiddlewaretoken', 'id'}}

    #     for key in formatted_values:

    #         question.key = formatted_values[key]

templates/quiz/createQuiz.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'css/quiz.css' %}">
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<div class="wrapper-content">
    {% comment %} Update Block - contains student scores {% endcomment %}

    {% if id %}
    <div class="container_body">
        <h1 class="heading_1"> Update Quiz: </h1>
        <form action="/quizzes/update/quiz/{{id}}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="quiz_container">
                {{field.error}}
                {{field.label_tag}}
                {{field}}
            </div>
            {% endfor %}
            <input class="submit_btn" type="submit" />
        </form>
        <form action="/quizzes/add" method="POST">
            {% csrf_token %}
            <input type="hidden" name="quiz_id" value="{{id}}">
            <input class="submit_btn" value='Add New Question' type="submit">
        </form>
    </div>

    <div class="question_container">
        <h1> Update Questions: </h1>
        {% if questions|length != 0 %}
        {% for question in questions %}
        <br>
        <div class="question_container">
            <div class="value_container">
                <a href="/quizzes/update/question/{{question.id}}">
                    <h2 class="question_title"> {{ question.title }} </h2>
                </a>
                <a class="deleteQuestion " href="quizzes/delete/question/{{question.id}}"> <i
                        class="fas fa-times-circle"></i> </a>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    {% if scores|length != 0 %}
    <div class="score_container">
        <h1> Scores: </h1>
        {% for score in scores  %}
        <div class="score">
            <br />
            <h2 class="scoreStudentName">{{score.first_name}} {{score.last_name}}:</h2>
            <h2 class="scoreStudentScore">{{score.score}}</h2>
            <br />
        </div>
        {% endfor %}
    </div>
    {% endif %}
    {% else %}
    {% comment %} Creation Block {% endcomment %}
    <h1 class="heading_1"> Create Quiz </h1>
    <div class="container_create_body">
        <form action="/quizzes/create" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="quiz_create_container">
                {{field.error}}
                {{field.label_tag}}
                {{field}}
            </div>
            {% endfor %}
            <input class="submit_btn" type="submit" />
        </form>
    </div>
    {% endif %}

</div>
{% endblock %}

templates/quiz/quiz.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'css/playquiz.css' %}">
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<div class="wrapper-content">
    <h1 class="heading_1"> Dashboard </h1>
    <div class="container_body">
        <h3> Quiz </h3>
        <br>
        <form action="/quizzes/submit" method="post">
            {% csrf_token %}
            <input type="hidden" name="id" value={{quiz}}>
            {% for question in questions  %}
            <div class="quiz_container">
                {% if question.image_path %}
                <img class="question_img" src="{{question.image_path.url}}" />
                {% endif %}
                <h2 class="question_title"> {{ question.title }} </h2>
                <div class="answer_container">
                    <h5 class="answer_choice"> {{ question.answer_1 }}</h5>
                    <input type="radio" name={{question.id}} value='1'>
                    <h5 class="answer_choice"> {{ question.answer_2 }}</h5>
                    <input type="radio" name={{question.id}} value='2'>
                    <h5 class="answer_choice"> {{ question.answer_3 }}</h5>
                    <input type="radio" name={{question.id}} value='3'>
                    <h5 class="answer_choice"> {{ question.answer_4 }}</h5>
                    <input type="radio" name={{question.id}} value='4'>
                </div>
            </div>
            {% endfor %}
            <input class="submit_btn" type="submit" />
        </form>

        <br>
    </div>

</div>
{% endblock %}

templates/quiz/quizzes.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'css/quizzes.css' %}">
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<div class="wrapper-content">
    <div class="heading_container">
        <div class="headings">
            <h1 class="heading_1"> Dashboard </h1>
            <h3> Quizzes </h3>
        </div>
    </div>
        {% if user.is_staff %}
        <a class="create_quiz" href='/quizzes/create'><button class="submit_btn" type="button"> Create Quiz
            </button></a>
        </div>
        <div class="container_body">
        {% for quiz in quizzes  %}
        <div class="quiz_container">
            <img class="quiz_img" src="{{quiz.image_path.url}}" />
            <a class="delete_quiz_button" href="quizzes/delete/quiz/{{quiz.id}}"> <i
                    class="fas fa-times-circle fa-2x"></i></a>
            </a>
            <div class="quiz_details">
                <a href="/quizzes/update/quiz/{{quiz.id}}">
                    {% comment %} <img class="entity_img" src="{{entity.image.url}}" /> {% endcomment %}
                    <h4 class="quiz_title"> {{ quiz.title }} </h4>
                    <h5 class="quiz_desc"> {{ quiz.get_classes_display }}</h5>
                    <h5 class="quiz_desc"> {{ quiz.get_level_display }}</h5>
                </a>
                </div>

        </div>
        {% endfor %}
        {% else %}
        {% for quiz in quizzes  %}
        <div class="quiz_container">
            {% if quiz.image_path %}
            <img class="quiz_img" src="{{quiz.image_path.url}}" />
            {% endif %}
            <a href="/quizzes/{{quiz.id}}">
                <div class="quiz_details">
                    <h4 class="quiz_title"> {{ quiz.title }} </h4>
                    <h5 class="quiz_desc"> {{ quiz.get_classes_display }}</h5>
                    <h5 class="quiz_desc"> {{ quiz.get_level_display }}</h5>
                </div>
            </a>
        </div>
        </div>
    {% endfor %}
    {% endif %}
    <br>
</div>

</div>
{% endblock %}

templates/quiz/submitted.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'css/homework.css' %}">
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<div class="wrapper-content">
    <h1>You scored {{score}}</h1>
    <br>
    <h1> Your score has been sent to your teacher </h1>
    {% if wrongAnswer|length == 0 %}
    <h1> Well Done you got all Questions Correct </h1>
    {% else %}
    {% for question in wrongAnswer  %}
    <div>
        <h2> You got the question: '{{question.title}}' wrong </h2>
        <h2> This was the correct answer: {{question.correct_answer_value}} </h2>
        <br>
    </div>
    {% endfor %}
{% endif %}
</div>

{% endblock %}